twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< HEAD
    form_themes: ['bootstrap_4_layout.html.twig']
=======
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
>>>>>>> origin/eya
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
